apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: 'https://kubernetes.default.svc'
  source:
    path: dev
    repoURL: 'https://github.com/bq-shubham-29/Traning_Assignment.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
