# This is a basic workflow to help you get started with Actions

name: count

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      count:
        type: number
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Give count to autoscaling group
        run: echo Hello, world!
      
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          aws autoscaling update-auto-scaling-group \
                            --auto-scaling-group-name my-ASG \
                            --min-size ${{inputs.count}} \
                            --max-size 2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
